### ISSUE TITLE
Reverse Geocoder option for Intersection/Blocks

### ISSUE THREAD

**Issue by dpeacock** [Esri/esri-leaflet-geocoder#105]
I would like to request an enhancement where the reverse geocoder accepts a parameter specifying the output format.  Currently it looks like I can only receive the closest address. It would also be helpful if the closest intersection could be returned, or closest block face.

**Comment by dpeacock** [comment]
I did a little digging into what the API supports and how things work currently.  It looks like this would be fairly straightforward to do today even with the following:

var reverseGeocoder = MapManager.geocodeService.reverse();
reverseGeocoder.params.returnIntersection = true;
reverseGeocoder.latlng([Lat, Long]).run(...)

However it looks like it returns some weird results for the intersection.  Use the example point [45.3679962, -75.77500239999999] it returns:
Address: "RR-38 & HWY-17B"

Without this it returns an address on Carling Ave.  It looks like the intersection functionality is not using the common names for the roads?

**Comment by jgravois** [comment]
i'm seeing all kinds of bogus results in Ottawa.  best i can tell we are storing both french and english streetnames and incorrectly calling the two an intersection.

![screenshot 2015-10-23 15 57 02](https://cloud.githubusercontent.com/assets/3011734/10706761/b88834f4-799e-11e5-9c9d-28d29c8c5640.png)

i'll notify the World Geocoding team and let you know what i hear back.

**Comment by jgravois** [comment]
good news!  they're not only already aware of the problem, its already been patched. 

look for more appropriate behavior after the next release of the World Geocoding Service (planned for December).

**Comment by dpeacock** [comment]
Great, thanks for the update.  Any thoughts of exposing returnIntersection directly in esri-leaflet-geocoder, or should it be used as I suggested?

**Comment by dpeacock** [comment]
Also in your example it's at least picking the correct road - just getting the french/english versions as the intersection. 

In my example I would have expected it to pick Carling Ave. as one of the points as it does with closest address.  However it was giving regional road names - I'm not sure if this is the same problem as the English/French issue you saw can you confirm?

**Comment by jgravois** [comment]
nothing wrong with the approach you're using now, but I agree it needs to actually be 'surfaced'.

I had hopes initially that the geocoder would behave after I used the same technique to apply `langCode`, but no joy.

**Comment by jgravois** [comment]
since the repro case you mentioned displays a tack in a location that lacks an actual intersection, i think its safe to say that its a result of the same problem (the geocoding engine's failure to throw out potential intersections composed of streets with identical geometry).  

as to how alternate streetnames are prioritized in the matching process for valid intersections, i don't know...

**Comment by jgravois** [comment]
feel free to take a look at #106 and provide more feedback if my fix doesn't seem sufficient.  either way, thanks for the feedback!

**Comment by dpeacock** [comment]
Took a look at #106 looks good, thanks for the quick response!
