### ISSUE TITLE
Not working with leaflet beta 2

### ISSUE THREAD

**Issue by reyemtm** [Esri/esri-leaflet-geocoder#107]
I am using the cdn from the geocoder example on the esri-leaflet page.

Uncaught TypeError: L.Util.limitExecByInterval is not a function Geosearch.js line 343

**Comment by jgravois** [comment]
i can't [reproduce](http://jsbin.com/duhimo/edit?html,output) what you're reporting using either `2.0.0` or our latest, [`2.0.1`](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.0.1).
if you can put together a repro case to share, i'd be happy to check it out

**Comment by reyemtm** [comment]
Might be a conflict with another plugin I'll look into it

**Comment by reyemtm** [comment]
The version on the github example:
    
    <script src="//cdn.jsdelivr.net/leaflet.esri/2.0.0-beta.6/esri-leaflet.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/leaflet.esri.geocoder/2.0.0/esri-leaflet-geocoder.css">
    <script src="//cdn.jsdelivr.net/leaflet.esri.geocoder/2.0.0/esri-leaflet-geocoder.js"></script>
   
does work with leaflet-beta-2. I was using the older version - esri-leaflet 1.0.0 and geocoder 1.0.2. from the esri-leaflet homepage.

Thanks

**Comment by jgravois** [comment]
awesome.

we'll be pushing edits to the site soon to show off the stuff that's compatible with Leaflet 1.0.0.
