### ISSUE TITLE
Limit Geocoder to Bounding Box. 

### ISSUE THREAD

**Issue by JRHutson** [Esri/esri-leaflet-geocoder#113]
It would be useful to be able to limit the geocoder suggestions to a bounding box rather than just the currently visible area. That way if a user is zoomed in to a high zoom level they would still receive relevant suggestions.

**Comment by jgravois** [comment]
i can see the use for defining a constructor option (which would override `useMapZoom`) to help with cases where the developer wants to apply a static filter for an area smaller than a country.

```js
var aoi = L.bounds([[36, -120], [32, -116]]);

var searchControl = L.esri.Geocoding.Controls.geosearch({
  searchBounds: aoi
}).addTo(map);
```

in [the source](https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Controls/Geosearch.js#L149), we'd just need something like this evaluated *before* the existing `useMapBounds` checks:

```js
_searchBounds: function () {
    if (this.options.searchBounds) {
      return this.options.searchBounds;
    }
   // ...
```

more info in JRHutson/Food-Resource-Map#62
i had a similar suggestion [here](https://github.com/Esri/esri-leaflet-geocoder/issues/38#issuecomment-64728650)

anyone game for submitting a PR which includes the appropriate tests and documentation updates as well?

**Comment by nathanhilbert** [comment]
I was looking for the same feature.  I'll take a stab at code, testing, and docs this afternoon.

**Comment by jgravois** [comment]
i just tagged [v2.0.3](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.0.3).  thanks again for PRing the new feature @nathanhilbert.

@JRHutson the new release should make its way to the [CDN](http://cdn.jsdelivr.net/leaflet.esri.geocoder/2.0.2/esri-leaflet-geocoder.js) shortly.  give me a holler if you have any trouble with it.

**Comment by JRHutson** [comment]
Thanks John! Working out some database challenges with the Foodbank to hopefully simplify updates schedule updates. So, front end updates might be a low priority for a bit. Awesome to see the feature is being added though.
