### ISSUE TITLE
Files for new 2.0.3 not available on cdn

### ISSUE THREAD

**Issue by skocher42** [Esri/esri-leaflet-geocoder#117]
I see that the new 2.0.3 release is completed with the new searchBounds parameter (yay!), and the updated readme shows an example that references the new version, but in fact that new version is not available yet on the cdn:

//cdn.jsdelivr.net/leaflet.esri.geocoder/2.0.3/esri-leaflet-geocoder.css
//cdn.jsdelivr.net/leaflet.esri.geocoder/2.0.3/esri-leaflet-geocoder.js

Are these files meant to be available on the cdn, or is there a new hosting location?

**Comment by jimaek** [comment]
In 2.0.3. the dist/ directory was removed https://github.com/Esri/esri-leaflet-geocoder/tree/v2.0.3
This caused the auto-update mechanism to fail.

**Comment by jgravois** [comment]
@skocher42 thanks for pointing out the problem.  

i've fixed our github release so the files will be up on the CDN as soon as @jimaek (or one of the other great folks at @jsdelivr) merges jsdelivr/jsdelivr#9407
