### ISSUE TITLE
Controlling level of zoom 

### ISSUE THREAD

**Issue by evanthoms** [Esri/esri-leaflet-geocoder#119]
When I hit enter after a query the map pans but then zooms in farther than I would like. Can I control this?

**Comment by jgravois** [comment]
yup.  by default we zoom to the extent of the matched feature.  you can set `zoomToResult` to false in the object constructor instead if you prefer and handle the situation when results are returned however you'd like.
```js
searchControl.on('results', function(data){
  // pan/zoom in to a static zoom level
});
```
[this sample](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) shows how to listen for results and draw markers on the map.

**Comment by evanthoms** [comment]
Thanks!

On Mon, Feb 1, 2016 at 3:58 PM, john gravois <notifications@github.com>
wrote:

> yup. by default we zoom to the extent of the matched feature. you can set
> zoomToResult to false in the object constructor instead if you prefer and
> handle the situation when results are returned however you'd like.
>
> searchControl.on('results', function(data){
>   // pan/zoom in to a static zoom level
> });
>
> this sample
> <http://esri.github.io/esri-leaflet/examples/geocoding-control.html>
> shows how to listen for results and draw markers on the map.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/esri-leaflet-geocoder/issues/119#issuecomment-178287164>
> .
>



-- 

Evan Thoms
US Geological Survey, Alaska Science Center
4210 University Drive, Anchorage,  AK 99508
voice: 907-786-7409	fax: 907-786-7401
ethoms@usgs.gov
