### ISSUE TITLE
npm start fails on windows

### ISSUE THREAD

**Issue by jmfolds** [Esri/esri-leaflet-geocoder#131]
Following the development instructions on windows 10, running "npm start" has the following issues:

1.) Use of single quotes in watch command fails. Using escaped double quotes to fix it. See: https://github.com/mikeal/watch/issues/109

2.) After updating to using escaped double quotes, http-server command after the "&" does not get called. Related: https://github.com/npm/npm/issues/4040

Here's what my updated start script looks like:
`"start": "watch \"npm run build\" src & http-server -p 5678 -c-1 -o"`

**Comment by jgravois** [comment]
sorry it took me so long to take a look at this.  switching from an `&` to a `|` ended up being enough to get things working correctly in [Git Bash](http://guides.beanstalkapp.com/version-control/git-on-windows.html) on Windows so i'm going to make the change in #139

i couldn't figure out how a way to execute simultaneous scripts that involve a subroutine in the built in WIndows Command Prompt ¯\_(ツ)_/¯

**Comment by jgravois** [comment]
i reverted my original change.  happy to accept a PR that uses [`concurrently`](https://github.com/Esri/cedar/pull/222/commits/400b586fe6d75e241056456b59bc8e544b04bb17) if anyone is interested in putting one together.
