### ISSUE TITLE
Label not visible

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-geocoder#143]
Although label is configured (https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Providers/ArcgisOnlineGeocoder.js#L5) it's not shown as title of the results. see the example http://esri.github.io/esri-leaflet/examples/geocoding-control.html

**Comment by jgravois** [comment]
labels are only displayed when more than one provider is used simultaneously.

https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Controls/Geosearch.js#L58
