### ISSUE TITLE
MapService Provider search text must match exactly

### ISSUE THREAD

**Issue by nickpeihl** [Esri/esri-leaflet-geocoder#148]
https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Providers/MapService.js#L57

I wonder if there's a valid reason to hard-code `contains(false)` into this line? When I use the MapService provider, I'd expect that typing search text and pressing enter would return all matching results. But setting `contains` to false forces the text to match exactly. I'd only expect an exact match if I waited for suggestions and selected one of those. 

In [this example](http://jsbin.com/locigeleso/edit?html,output) I'd expect to be able to type in `maine` and press enter and the map would zoom to Maine. Instead, I have to type in `Maine` exactly as it would appear to see the result. 

Is there another reason for `contains(false)` that I'm missing?

**Comment by jgravois** [comment]
my first instinct is that pat was trying to make sure and isolate a single result.  

we'll need to do a little testing to confirm the behavior when more than one match is returned but in general i agree that it'd probably be more appropriate to omit the `contains()` method call entirely and improve the *fuzziness* of the search.

if you can spare the time, please submit a PR and we can continue the discussion there.

**Comment by nickpeihl** [comment]
Fixed by  8b68a45
