### ISSUE TITLE
Merge featureLayerProvider geometries in the results

### ISSUE THREAD

**Issue by AnnieGitUrGun** [Esri/esri-leaflet-geocoder#151]
I have a case where searching for certain ZIP codes returns 2 separate polygons (because the ZIP code spans 2 counties). I need to be able to merge them to return a single polygon. Before I switched to this geocoder I returned the features and used L.esri.Util.arcgisToGeojson to push the geometries into a feature collection and then merged them using turf.js. 

```
getCityZipBoundary: function(data){
     var df = $q.defer();
     var features = data.features;
     var featureCollection = {
         type: 'featureCollection',
         features: []
     };
     for (var i = features.length - 1; i >= 0; i--) {
         var feature = L.esri.Util.arcgisToGeojson(features[i]);
         featureCollection.features.push(feature);
     }
         var mergedPolygon = turf.merge(featureCollection);
         df.resolve(mergedPolygon);
         return df.promise;
}
```

Now that I'm using this geocoder plugin I'm not sure how I would be able to merge the geometries.

**What I was going to try next but I'm extremely hesitant:**
It looks like I would need to add code to the suggestions function that checks to see if the input text matches suggestions.text and if they do then change the magicKey value to null. 

```
suggestions: function(text, bounds, callback) {
            var query = this.query().where(this._buildQuery(text)).returnGeometry(true);
            if (bounds) {
                query.intersects(bounds)
            }
            if (this.options.idField) {
                query.fields([this.options.idField].concat(this.options.searchFields))
            }
            var request = query.run(function(error, results, raw) {
                if (error) {
                    callback(error, [])
                } else {
                    this.options.idField = raw.objectIdFieldName;
                    var suggestions = [];
                    var count = Math.min(results.features.length, this.options.maxResults);
                    for (var i = 0; i < count; i++) {
                        var feature = results.features[i];
                        suggestions.push({
                            text: this.options.formatSuggestion.call(this, feature),
                            magicKey: feature.id
                        })
                    }
                    <<<Insert code here to change magicKey value to null?>>>
                    callback(error, suggestions.slice(0, this.options.maxResults).reverse())
                }
            }, this);
            return request
        }
```

Then, in results function, since you wouldn't have a key it would make a generic search and then I could merge the geometries the way I did before.

```
results: function(text, key, bounds, callback) {
            var query = this.query();
            if (key) {
                query.featureIds([key])
            } else {
                query.where(this._buildQuery(text))
            }
            if (bounds) {
                query.within(bounds)
            }
            return query.run(L.Util.bind(function(error, features) {
                var results = [];
                <<<Insert code here to merge features?>>>
                for (var i = 0; i < features.features.length; i++) {
                    var feature = features.features[i];
                    if (feature) {
                        var bounds = this._featureBounds(feature);
                        var result = {
                            latlng: bounds.getCenter(),
                            bounds: bounds,
                            text: this.options.formatSuggestion.call(this, feature),
                            properties: feature.properties,
                            geojson: feature
                        };
                        results.push(result)
                    }
                }
                callback(error, results)
            }, this))
        },
```

Am I on the right track or is this a terrible idea or am I completely missing the obvious solution?

**Comment by jgravois** [comment]
thanks for taking the time to outline your goal and progress so thoroughly.  

it sounds like you are saying that when you see duplicate search results listed as suggestions you'd like to have access to the entire collection after making a selection.  is that correct?

its just a gut reaction, but i think we should probably make sure no duplicates appear in the list of suggestions to begin with.

**Comment by jgravois** [comment]
@AnnieGitUrGun i'm happy to try and provide assistance with your issue.  are you still interested and available to answer my previous question, troubleshoot and discuss further?

**Comment by AnnieGitUrGun** [comment]
Apologies for not following up sooner.

Well, these aren't exactly duplicates but in a list they would appear as such. Let me give you a concrete example. In the example below I've searched for White Hall. 
![image](https://cloud.githubusercontent.com/assets/1444409/20043458/c4d35a34-a45b-11e6-9f62-3d7cffb3061e.png)

The White Hall ZIP code spans 2 counties- Baltimore and Harford. The picture below shows the ZIP code in its entirety (and also what I was able to do before switching to this geocoder).

![image](https://cloud.githubusercontent.com/assets/1444409/20043581/8f91bae4-a45d-11e6-96dc-6e17cd8b6cd1.png)

Unfortunately, the data provider decided to clip the ZIP codes to the county boundaries (which makes no sense but that's what I'm stuck with for now). This is why there are two entries for White Hall, MD 21161. If I select one or the other I will only get one half of the ZIP code when I need to get the whole thing:

![image](https://cloud.githubusercontent.com/assets/1444409/20043751/bc489056-a45f-11e6-995d-1a252ab48ed9.png)
 

So in my initial question I was trying to figure out how I could merge the suggestions and the geometries.

Thanks for your help!

**Comment by jgravois** [comment]
thanks for confirming that my understanding of the workflow was correct.

the first (and best, solution) would be to post process the data you purchased prior to publishing your service.  all you'd need is a quick [`dissolve`](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/dissolve.htm).

if this isn't an option for you, i feel like the geocoder *should* be smart enough to not display list items if the formatted text is identical to an item that has already been added. 

once an item is selected by the user, **all** results with identical formatted text should be passed through in the results.

you are seeing the problem when using the `featureLayerProvider`, correct? 
can you make a sample service publicly available for me to test with (even if it only includes a small subset of the original data)?

**Comment by AnnieGitUrGun** [comment]
Correct. Below is the service I'm hitting:
http://geodata.md.gov/imap/rest/services/Boundaries/MD_PoliticalBoundaries/FeatureServer/3

**Comment by jgravois** [comment]
i've proposed a fix to the geosearch control.  would you be kind enough to test it out and confirm that it solves the problem at hand?

**Comment by AnnieGitUrGun** [comment]
I've tested and can confirm it solves my problem. Thank you!

**Comment by jgravois** [comment]
awesome.  thanks!
