### ISSUE TITLE
when bundling with webpack, why is the babel loader still required?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-geocoder#152]
https://github.com/Esri/esri-leaflet-webpack-example/pull/1

**Comment by DecafManiac** [comment]
there is some ES6 code that require babel to work properly

**Comment by jgravois** [comment]
you'll have to be a little more specific.  as far as i can tell, the code here is the same as in [esri-leaflet](https://github.com/Esri/esri-leaflet) core, and the babel loader isn't necessary for that.

**Comment by jgravois** [comment]
in the interest of inbox zero, probably safe to just assume @DecafManiac is right.
