### ISSUE TITLE
Unable to search places a second time that are not within the map bounds

### ISSUE THREAD

**Issue by PHR1990** [Esri/esri-leaflet-geocoder#153]
Hi,

Perhaps I am doing something wrong, but, attempt to perform this on the demo app here:

http://esri.github.io/esri-leaflet/examples/search-map-service.html

Look for:
1st
Porto Alegre, Cristovao Colombo

2nd
Rua dona adda mascarenhas de moraes

It won't do anything... both streets are on the same city (Porto Alegre) Country is Brazil.

I don't know if I am doing something wrong... but I attempted this several times.

Rgds,
Pedro.

**Comment by jgravois** [comment]
the default behavior of the control is to restrict results to the current extent of the map when zoomed into level 12 or closer (see the constructor option [`useMapBounds`](http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#options)).

if you'd like to make sure the control *never* filters results outside the current extent, use `false`.

```js
L.esri.Geocoding.geosearch({
  useMapBounds: false
}).addTo(map);
```

**Comment by PHR1990** [comment]
Wow, I can't believe I've missed that. I've found on the documentation 'searchBounds:null' and I thought it would force this behavior.

Thanks!

**Comment by jgravois** [comment]
no worries. `searchBounds` provides an option to filter by an artificial, *static* extent.
