### ISSUE TITLE
Prevent firing request if input text is too short

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-geocoder#159]
Typing enter in the geocoder input is sufficient to run queries _without any character_ against the featureLayerProvider. By doing that, users get as result all features available. 
It'd be better to have the possibility to limit such behavior, for example by introducing a constraint that defines the minimum number of characters required to run a query.
It's basically the same approach there is for _auto_ suggestions where the minimum characters are 2 (hard coded https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Controls/Geosearch.js#L278).

**Comment by jgravois** [comment]
to make that change you'd want to add the constraint you describe [here](https://github.com/Esri/esri-leaflet-geocoder/blob/ec6f6a153336194aaacc0c1d30c44e9deb1d7b18/src/Controls/Geosearch.js#L225).

if you're interested in putting together a pull request, i'd be happy to help you.
