### ISSUE TITLE
Minor css issues with ie11

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-geocoder#160]
The suggestion panel is not hided when there are no suggestions.
![errore_1_css_ie11](https://cloud.githubusercontent.com/assets/17850886/20139708/aad8d00e-a687-11e6-9df6-e404e3192795.png)

The suggestion panel is not aligned with the input box
![errore_2_css_ie11](https://cloud.githubusercontent.com/assets/17850886/20139717/bffa4e40-a687-11e6-8e25-6fa261d50939.png)

**Comment by jgravois** [comment]
today i noticed an issue w/ the size and alignment of the unexpanded search box in chrome 55 that look to be the same as i saw historically in IE.  will try to find time to investigate soon.

![screenshot 2016-12-19 15 22 22](https://cloud.githubusercontent.com/assets/3011734/21332685/03b93204-c5ff-11e6-8728-953b84a4ca1b.png)
