### ISSUE TITLE
L.esri.Geocoding.Geosearch:  Problem with using zoomToResult and useMapBounds together

### ISSUE THREAD

**Issue by DCDiaz** [Esri/esri-leaflet-geocoder#165]
* Browser and version: Chrome 54.0.2840.99, Edge 38.14393.0.0, Firefox 50.0

* Version of Leaflet (`L.version`): 1.0.1

* Version of esri Leaflet (`L.esri.VERSION`): 2.0.4

*Demo: http://meetingalertpro.com/test/

*Current Options: {'useMapBounds':false, 'collapseAfterResult':false, 'expanded':true}

Steps to reproduce the error:

1. In the map's search field, enter "Denver, CO".  "Denver, Colorado, United States" will appear in the search suggestions, and when selected, the map will zoom to that location.  Good.

2. Next, while still zoomed in to Denver, enter "Fraser, CO" in the map's search field.  "Fraser, Colorado, United States" will appear in the search suggestions, and when selected, the map will zoom to that location.  Good.

3. Now, while still zoomed in to Fraser, search for "Denver, CO" again.  "Denver, Colorado, United States" will NOT appear in the search suggestions. Not good. Since I've set 'useMapBounds':false, I would expect "Denver, Colorado, United States" to still appear among the search suggestions.

This example can be extended to *all* cases of searching for any large city and then searching for any small town in the world.  This issue seems to be related to the zoom level that is automatically reached when using 'zoomToResult'.  The automatic zoom is greater on small towns than it is on large cities.  When automatically zooming to a small town after a search, it seems to reach a level that overrides my option settings and forces 'useMapBounds':true, even while I have it set to 'false'.  After auto zooming to a small town, I've found that I need to zoom out two levels before 'useMapBounds' behaves as 'false' again. 

Thank you for your attention to this issue!

**Comment by jgravois** [comment]
this is a bug. 

until it's resolved, you can work around the problem by explicitly including the `arcgisOnlineProvider` in the geosearch constructor.

```js
var searchControl = L.esri.Geocoding.geosearch({
  useMapBounds:false,
  providers: [
    L.esri.Geocoding.arcgisOnlineProvider()
  ]
}).addTo(map);
```

**Comment by DCDiaz** [comment]
Thanks for the work-around for this -- it works.  Will you update this Issue  when the bug is resolved?

**Comment by jgravois** [comment]
absolutely.

**Comment by jgravois** [comment]
the fix has landed in `master` and will appear in our next tagged release.  thanks for reporting it!
