### ISSUE TITLE
geosearch not firing mousedown on phone

### ISSUE THREAD

**Issue by walliby** [Esri/esri-leaflet-geocoder#171]
The mousedown event appears to not be captured on my phone using:

Moto Z Play
Chrome 55.0.2883.91
Android 6.0.1
Using geocoder 2.2.3

When I use the geosearch control, it is providing recommended addresses but when I select one it highlights and nothing happens. 

It is working fine on my phone with Firefox, and also on my desktop and my iPad.

Would it make sense to add touchstart event listener?

**Comment by jgravois** [comment]
based on the fact that Chrome 55 unified touch and mouse events, my hunch is that the most appropriate addition would be [`pointerover`](https://developers.google.com/web/updates/2016/10/pointer-events).

**Comment by jgravois** [comment]
i just ran my own test in Chrome 55.0.2883.91 on android and i wasn't able to reproduce the problem you described.

what did you end up doing on your side?

**Comment by walliby** [comment]
I just retested and still have the same issue. I don't have the issue on iOS or my desktop. On the devices listed below, I get address recommendations and when I select them, they highlight in blue but the map doesn't update to the address. Seems like the event is not firing. I have not tried to resolve this yet as most of my users are on iPhones.

**I am using the following libraries**
https://unpkg.com/leaflet@1.0.2/dist/leaflet.css
https://unpkg.com/esri-leaflet-geocoder@2.2.3/dist/esri-leaflet-geocoder.css
https://unpkg.com/leaflet.markercluster@1.0.0/dist/MarkerCluster.css
https://unpkg.com/leaflet@1.0.2/dist/leaflet-src.js
https://unpkg.com/esri-leaflet@2.0.7
https://unpkg.com/esri-leaflet-geocoder@2.2.3
'https://unpkg.com/leaflet.markercluster@1.0.0/dist/leaflet.markercluster.js

**Here is how I am adding the search control**
L.esri.Geocoding.geosearch({
	useMapBounds: false
}).addTo(map);

**Here are the devices I am testing on**
Samsung galaxy s6
Chrome 56.0.2924.87
android 6.0.1

Moto Z Play
Chrome 55.0.2883.91
android 6.0.1

**Comment by walliby** [comment]
Interesting, I just tried the example on my phone (http://esri.github.io/esri-leaflet/examples/geocoding-control.html) and that worked fine. Must be something about my specific implementation.

**Comment by walliby** [comment]
Maybe it is because I am not using leaflet 1.03. I see that they just released this on 1/23 and sounds like they made some changes related to pointerevents. I can't test at the moment but will try changing my leaflet version soon.

One of the main highlights is the handling of dblblick events for web browsers which support PointerEvents. Until now, the only browser which used PointerEvents were Internet Explorer and Edge; but now that Chrome has enabled support in version 55, the Leaflet code for checking for double clicks and touchscreens had to change.

**Comment by walliby** [comment]
That fixed it! Just changed leaflet from 1.0.2 to 1.0.3.

**Comment by jgravois** [comment]
glad to hear it.
