### ISSUE TITLE
Custom ArcGIS Geocode Service Provider not providing?

### ISSUE THREAD

**Issue by nikolaswise** [Esri/esri-leaflet-geocoder#174]
When attempting to spin up a local government geocode service – an ArcGIS service for what it's worth - it doesn't seem to play nice with the geocoder UI:

JS Bin here: https://jsbin.com/fipixabeno/edit?html,css,js,console,output

@jgravois maybe knows such stuff?

**Comment by jgravois** [comment]
jsbin is throwing a `500` when i try and open your link.  can you copy/paste your code straight into the issue 🍰 ?

**Comment by nikolaswise** [comment]
Sure thing @jgravois 
```

var map = L.map('map', {
  trackResize: true,
  center: [45.528, -122.680],
  zoom: 13,
  zoomControl: false,
  scrollWheelZoom: false
});

L.esri.tiledMapLayer({
  url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Basemap_Color_Complete/MapServer'
}).addTo(map);

var pbotGeocoder = window.L.esri.Geocoding.geocodeServiceProvider({
  url: 'https://www.portlandmaps.com/arcgis/rest/services/Public/Geocoding_PDX/GeocodeServer'
});

var searchControl = window.L.esri.Geocoding.geosearch({
  providers: [pbotGeocoder],
  position: 'topright',
  zoomToResult: true,
  useMapBounds: 10,
  allowMultipleResults: false
}).addTo(map);
```

**Comment by jgravois** [comment]
| Option | Type | Default | Description |
| -- | -- | -- | -- |
| allowMultipleResults | Boolean | true | If set to true and the user submits the form *without a suggestion*, the control will geocode the current text in the input. |

`allowMultipleResults` has to be set to true in order for the geosearch control to submit the content of the input for geocoding when the service in use doesn't expose a `/suggest` operation.

**Comment by nikolaswise** [comment]
Well how about that.
