### ISSUE TITLE
Search is limited to the current screen extent

### ISSUE THREAD

**Issue by JerryWorkman** [Esri/esri-leaflet-geocoder#176]
Search is limited to the current screen extent. The [ESRI demo site](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) exhibits the same problem.

I'm not sure if this is a bug or feature. The ESRI Javascript API uses the extent of the entire map, not the zoomed extent. Users expect to be searching the entire extent of the map. 

I suggest that you make this a configuration option.

**Comment by jgravois** [comment]
the default behavior is to filter results based on the current extent of the map *only* when users are zoomed into level `12` or closer. configuration option to override that behavior is already exposed.

```js
// http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#options
L.esri.Geocoding.geosearch({ useMapBounds: false });
```

**Comment by JerryWorkman** [comment]
John,

Thanks. Works as advertised (when you read the docs).

One more thought. It would be useful to search a fixed extent. For instance
the original extent of the map.

Jerry

**Comment by jgravois** [comment]
that constructor option is called `searchExtent`

**Comment by JerryWorkman** [comment]
Missed that too.

**Comment by JerryWorkman** [comment]
John,

Great job on this control. I've added this to find the "best" result.

// listen for the results event and add the best result to the map
searchControl.on("results", function (data) {
  results.clearLayers();
  var error_msg = "No results from server.";
  if (data.results.length === 0) {
    Utility.Alert(map, "Error", error_msg);
  }
  //if USA.PointAddress exists use it
  var found = false;
  for (var i = 0; i <= data.results.length - 1; i++) {
    var record = data.results[i];
    // First priority
    if (record.properties.Loc_name == 'USA.PointAddress') {
      found = true;
      results.addLayer(L.marker(record.latlng));
      break;
    }
  }
  // See if there is a street address
  if (!found) {
    for (var i = 0; i <= data.results.length - 1; i++) {
      if (record.properties.Loc_name == 'USA.StreetAddress') {
        found = true;
        results.addLayer(L.marker(record.latlng));
        break;
      }
    }
  }
  // Last effort take anything found
  if (!found) {
    for (var i = 0; i <= data.results.length - 1; i++) {
      results.addLayer(L.marker(record.latlng));
    }
  }
});

Jerry
