### ISSUE TITLE
Once searched, the new search auto complete is not working?

### ISSUE THREAD

**Issue by jeetu-gis** [Esri/esri-leaflet-geocoder#179]
Once an address search is done, unable to clear it for new search address. It repeatedly displays same addresses in the drop down.

**Comment by jgravois** [comment]
i can't reproduce the error you describe in the sample below.  can you provide more info please?

http://esri.github.io/esri-leaflet/examples/geocoding-control.html

**Comment by jgravois** [comment]
happy to reopen and provide more assistance if/when you can provide more information about what is necessary to induce the error.
