### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by mblais29** [Esri/esri-leaflet-geocoder#185]
I recently installed esri-geocoder-2.2.6 on leaflet 1.2 and I get this error **Uncaught TypeError: Cannot read property 'extend' of undefined** when the map loads any idea why?

![error 2](https://user-images.githubusercontent.com/8483022/31983219-385871b8-b911-11e7-90bb-ac0da53c767e.jpg)
![error 1](https://user-images.githubusercontent.com/8483022/31983220-38727b94-b911-11e7-8907-016fe27c5efe.jpg)

**Comment by jgravois** [comment]
my best guess is that you forgot to include a reference to `esri-leaflet` itself, which this geocoder also depends on.

you can find a working sample in the README here and on the Esri Leaflet website

http://esri.github.io/esri-leaflet/examples/geocoding-control.html

**Comment by jgravois** [comment]
happy to chat more if you have any other questions.
