### ISSUE TITLE
Geocode Service Error: Uncaught TypeError: n.suggestions is not a function

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-geocoder#192]
I was prepping for a workshop and encountered an issue when using custom ArcGIS Server geocode services.  This issue does not occur using the Esri World Geocoding Service or Feature Layer search.  I have a sample with multiple test geocode services at https://codepen.io/pmckinney/pen/bLqEWX.

Console error (Chrome 64):
![esri-geocoder-error-2-9-2018](https://user-images.githubusercontent.com/12861454/36032971-a7678380-0d7d-11e8-85bc-4119fbd2b81f.PNG)

Console error (IE 11):
![esri-geocoder-error-ie-2-9-2018](https://user-images.githubusercontent.com/12861454/36033267-8817f66c-0d7e-11e8-91a6-0eaaec38a605.PNG)

Error sample uses:
- Leaflet 1.3.1
- Esri Leaflet 2.1.2
- Esri Leaflet Geocoder 2.2.8

I have a working map located at http://gis.ccpa.net/maps/recycling-disposal/.

Working app uses:
- Leaflet 1.0.3
- Esri Leaflet 2.0.7
- Esri Leaflet Geocoder 2.2.6

**Comment by jgravois** [comment]
hi @pmacMaps! have you tried using the plugin's sourcemap to step through the code to see if you can identify the root of the problem?

**Comment by pmacMaps** [comment]
Haven't had time yet.  And to be honest, not sure when I'll have time to look into it.

**Comment by jgravois** [comment]
you just need to provide an instance of `geocodeServiceProvider` to the control instead of `geocodeService`

```js
// not L.esri.Geocoding.geocodeService()
var ccpaRoadsProvider = L.esri.Geocoding.geocodeServiceProvider({
    url: '//gis.ccpa.net/arcgiswebadaptor/rest/services/Roads_Locator/GeocodeServer'
});

var geosearchControl = L.esri.Geocoding.geosearch({
    providers: [ccpaRoadsProvider]
}).addTo(map);
```
![screenshot 2018-02-14 11 38 06](https://user-images.githubusercontent.com/3011734/36224156-8df8f6f2-117b-11e8-842f-cdcee9d8daf2.png)
