### ISSUE TITLE
TypeError: map.attributionControl is undefined ( Geosearch.js:202:4)

### ISSUE THREAD

**Issue by albabrobia** [Esri/esri-leaflet-geocoder#194]
Hello,
when trying to add "Esri-leaflet-geocoder", the browser respond me with the error:
 'addAttribution' of undefined /map.attributionControl is undefined.

The error indicates me this two lines of Geosearch.js file:
var credits = this._geosearchCore._getAttribution();
    map.attributionControl.addAttribution(credits);

Could be an error related by using "Bootleaf" template plugin?

When I use the Esri plugin in a simple Leflet map, in the attribution credits appears automatically "Powered by Esri". I was thinking in an error realted to "incompatibility" between both plugins (Bootleaf and Esri Leaflet) attribution controls.

Any suggestion...?

Thank you!

**Comment by pmacMaps** [comment]
I have a working implementation of BootLeaf and various Esri Leaflet plugins at https://gis.ccpa.net/maps/recycling-disposal/.  

What version of the Geocoder plugin are you using?  Do you have a working demo on CodePen/JSFiddle/etc?    Below are the versions of various assets in my map:

- Bootstrap 3.3.7
- jQuery 3.3.1
- Leaflet 1.0.3
- Esri Leaflet 2.0.7
- Esri Leaflet Geocoder 2.2.6

**Comment by albabrobia** [comment]
Thanks, pmacMaps! After to check assets versions were the same for me, I could realize the problem was related for sure only to the attribution controls. 

I have removed all the attribution options that come with the Bootleaf template (L.map "attributionControl: false"...) and finally the "Esri Leaflet Geocoder" is working. 

Sorry I am very beginner in programming...

Thank you for your help! :)

**Comment by jgravois** [comment]
i'd call it a bug that this plugin currently _requires_ Leaflet's attribution control to be enabled.

**Comment by pmacMaps** [comment]
You could also check out the Esri Calcite Maps project (https://github.com/Esri/calcite-maps).

It uses Bootstrap and looks pretty nice. I actually prefer it to BootLeaf.
