### ISSUE TITLE
Geosearch control does not respond to copy/paste action

### ISSUE THREAD

**Issue by UsgsMonkey** [Esri/esri-leaflet-geocoder#195]
The problem is after a copy/paste, the control doesn't seem to respond to the ensuing 'enter-key' keystroke.  I believe this may solve the problem...

see lines 811-813 (esri-leaflet-geocoder-debug.js):
`	    leaflet.DomEvent.addListener(this._input, 'keyup', leaflet.Util.throttle(function (e) {
	      var key = e.which || e.keyCode;
	      var text = (e.target || e.srcElement).value;
`

replace with:
`	    leaflet.DomEvent.addListener(this._input, 'keyup input', leaflet.Util.throttle(function (e) {
	      var key = e.which || e.keyCode;
	      var text = (e.target || e.srcElement).value;
`

**Comment by jgravois** [comment]
thanks for the heads up @UsgsMonkey! would you be willing to submit the proposed code change via a [pull request](https://help.github.com/articles/about-pull-requests/)?

https://github.com/Esri/esri-leaflet-geocoder/blob/f369a0c3fc9fae169a56cf0827573a5fe62f0a47/src/Controls/Geosearch.js#L319

**Comment by UsgsMonkey** [comment]
Honestly, I haven't had much interaction on that level with GitHub before.  What's involved?

**Comment by UsgsMonkey** [comment]
Ok... got my SSH Key defined in my profile and successfully downloaded esri-leaflet-geocoder w/ my git client. Now what?

**Comment by jgravois** [comment]
no need to apologize.

its not required, but its a good idea to create a branch before you commit your own changes. i'm fond of the documentation below, but there are other good resources out there too.

https://guides.github.com/introduction/flow/

**Comment by UsgsMonkey** [comment]
I ran npm test but am not sure how to read the results.  Is there anything I should look for there to ensure it's kosher?

**Comment by UsgsMonkey** [comment]
Ok I've completed the pull request.  Still not sure about reading the test results, but it looks good *shrug* :)

**Comment by jgravois** [comment]
see #196 for more info
