### ISSUE TITLE
Unpkg CDN not Working for 2.2.10

### ISSUE THREAD

**Issue by dsusini** [Esri/esri-leaflet-geocoder#201]
Not sure where else to put this...but we are using the unpkg CDN pointing to the latest minor version of this plugin for a client, using @2.2.  This morning it looks like the latest version number was updated to 2.2.10, but the CDN does not return code for that version number.  We had to point specifically to 2.2.9 for it to work again.

To be specific, the /dist folder is empty.

Just wanted to inform someone.

**Comment by jgravois** [comment]
thanks for the report. we've had corrupt npm tarballs before too (`v2.2.5`, `v2.2.7`).

my hope is that the tweak in #202 will lead to more consistent behavior.

`v2.2.11` will be up in a few minutes.
