### ISSUE TITLE
Results shows country specific but searching is done all over the world 

### ISSUE THREAD

**Issue by anujkamat29** [Esri/esri-leaflet-geocoder#203]
I have made search results country-specific, however, when searched(typed and insantly press enter) it displays markers all over the world. It only occurs when there is no focus over the search results.

Is there any way to get desired markers by searching only in a particular country without using searchBounds?

**Comment by jgravois** [comment]
nice catch!

we likely just need to port the relevant logic from `ArcgisOnlineGeocoder.suggest()` into `ArcgisOnlineGeocoder.results()`

https://github.com/Esri/esri-leaflet-geocoder/blob/cf3e30bf7cfb73bc63e0162d9eac544f348971b6/src/Providers/ArcgisOnlineGeocoder.js#L16-L18

do you think you could test this out and submit a pull request? i'm out of the office for a couple more days, but happy to review when i get back (and perhaps @pmacMaps can provide guidance in the meantime).

**Comment by jgravois** [comment]
released as [`v2.2.13`](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.2.13) :tada:
