### ISSUE TITLE
After a user search for a text, searched text disappear from search box

### ISSUE THREAD

**Issue by zubairkhanafridi** [Esri/esri-leaflet-geocoder#206]
I want my text to stay in search box after i search for a text but currently i am unable to do it. How to achieve this functionality?

**Comment by jgravois** [comment]
after a result is successfully geocoded, the plugin calls [`clear()`](https://github.com/Esri/esri-leaflet-geocoder/blob/12edee9706fd357ac5263ca24594ec71a3fe8295/src/Controls/Geosearch.js#L202). 

internally, one of the things that method does is blank out the input text.

https://github.com/Esri/esri-leaflet-geocoder/blob/12edee9706fd357ac5263ca24594ec71a3fe8295/src/Controls/Geosearch.js#L142

you could either:
1. comment out that line, rebuild the plugin and load your own _customized_ `esri-leaflet-geocoder` in your app (more info on how to do that [here](https://github.com/Esri/esri-leaflet-geocoder#development-instructions))
2. continue to use the plugin we've published and write some logic of your own to (re)set the `<input>` value _after_ a result has been fetched.
