### ISSUE TITLE
how to integrate with react

### ISSUE THREAD

**Issue by baoqger** [Esri/esri-leaflet-geocoder#208]
hi, 
I want to implement geo search function in my react app, the function can be done with this online demo: 
https://codepen.io/exomark/pen/dafBD
```
  var searchControl = new L.esri.Controls.Geosearch().addTo(map);

  var results = new L.LayerGroup().addTo(map);

  searchControl.on('results', function(data){
    results.clearLayers();
    for (var i = data.results.length - 1; i >= 0; i--) {
      results.addLayer(L.marker(data.results[i].latlng));
    }
  });
```
But how to do this in react app?

**Comment by jgravois** [comment]
hi @baoqger, we don't write code to order, but if you decide to take a stab at it yourself, the resources below might be helpful.

* https://github.com/facebook/create-react-app
* https://stackoverflow.com/questions/38500397/i-cant-get-esri-leaflet-to-work-with-reactjs-basemaplayer-of-undefined
* https://github.com/ungoldman/github-user-map (an oldie but a goodie)

**Comment by rufoot** [comment]
@jgravois That works well.
I am trying to add the geo address in the marker tooltip as below.

![Screen Shot 2019-04-22 at 6 31 56 AM](https://user-images.githubusercontent.com/43410634/56481812-8b502400-64c9-11e9-8c29-8a2e80a82563.png)

Do you have any idea?

**Comment by jgravois** [comment]
@rufoot what have you tried?

**Comment by rufoot** [comment]
@jgravois 
I have followed this.
[https://codesandbox.io/s/2wy7v2orwr](url)

As you know there isn't any part for displaying the geo address.

**Comment by jgravois** [comment]
i'd suggest reading the tutorial below.

> #### [Leaflet Quick Start Guide](https://leafletjs.com/examples/quick-start/)
> This step-by-step guide will quickly get you started on Leaflet basics, including setting up a Leaflet map, working with markers, polylines and popups, and dealing with events.
