### ISSUE TITLE
Geocoding fails when searchBounds are already in L.latLngBounds format

### ISSUE THREAD

**Issue by fungjj92** [Esri/esri-leaflet-geocoder#209]
Hi 👋 

I am building a React app that uses `React-leaflet`, esri-leaflet-geocoder.
Zooming into the map to 12+ and then typing the ESRI geocoder results in the following error with stack trace:
![image](https://user-images.githubusercontent.com/10568752/48735410-4e2fef00-ec16-11e8-8b84-629054f2850b.png)

The bounds come in formatted as `L.latLngBounds` but are [transformed
 ](https://github.com/Esri/esri-leaflet-geocoder/blob/cf3e30bf7cfb73bc63e0162d9eac544f348971b6/src/Tasks/Suggest.js#L30) with the expectation that they're `latLng`s, which results in an empty `L.latLngBounds` object. A class check for `latLngBounds` before transforming it/or not would probably do it.

Assuming you don't want search bounds on the geocode search, this error can be avoided by setting the geocoder option `{ searchBounds: false }` https://github.com/Esri/esri-leaflet-geocoder/pull/115

**Comment by jgravois** [comment]
thanks for the detailed report @fungjj92 and forgive me if i'm belaboring something you already know.

by default, we set the constructor option `useMapBounds` internally to `12` so that the current extent of the map will be passed along in requests only when users are zoomed in at least that far. it is also possible to set that property using a `boolean` to get the control you described at _all_ zoom levels.

`searchBounds` is an optional constructor option we added later for devs that wanted to consistently supply a hardcoded bounding box regardless of the current extent of the map.

```js
const southWest = L.latLng(29.30, -99.71);
const northEast = L.latLng(31.34, -95.57);
const searchBounds = L.latLngBounds(southWest, northEast);
// ...
L.esri.Geocoding.geosearch({
  searchBounds
}).addTo(map);
```

if, as you said, you don't want _any_ bounds to be appended to requests, it'd be best to set `useMapBounds: false` and skip setting `searchBounds` entirely.

does that make sense?
does it produce the behavior you'd expect?

**Comment by fungjj92** [comment]
Thanks for the speedy and thorough response! As you suggested I tried the `useMapBounds` geocoder option instead of `searchBounds` (which I missed 🤷‍♀️ ). I don't see the error in my original issue log 🎉🌮 I still get a similar, but not breaking, [error](https://github.com/Esri/esri-leaflet-geocoder/blob/cf3e30bf7cfb73bc63e0162d9eac544f348971b6/src/Classes/GeosearchCore.js#L48) now in Leaflet itself. Below, you can see the transformation issue to `L.latLngBounds`.

![screen shot 2018-11-20 at 9 17 01 am](https://user-images.githubusercontent.com/10568752/48779207-1328cc80-eca5-11e8-8880-1fa7750a6fff.png)

This error goes away with option `zoomToResult: false`. Still, the map zooms to any selected result, which is my desired behavior.

**Comment by jgravois** [comment]
good to hear.

can you share either a simplified codepen or at least a snippet of how you are instantiating the control?

**Comment by jgravois** [comment]
i put together a working sample using your own code and i'm not able to reproduce the error you describe.

https://jsbin.com/jizoqey/edit?html,output

if you can provide more info to help it'd be sincerely appreciated.

**Comment by fungjj92** [comment]
I'm checking out your codepen, and there's no issue there. I wonder if it makes a difference that I am using react-leaflet. Here's a snippet of my React component that brought up this issue originally, with some simplifications:
```
import React, { Component, createRef } from 'react';
import * as esri from 'esri-leaflet-geocoder';
import { Map as LeafletMap } from 'react-leaflet';

class Map extends Component {
    constructor() {
        super();
        this.mapRef = createRef();
    }

    componentDidMount() {
        const geocoderUrl = 'https://utility.arcgis.com/...';
        const map = this.mapRef.current.leafletElement;
        const geocoder = new esri.Geosearch({
            providers: [
                new esri.ArcgisOnlineProvider({
                    url: geocoderUrl,
                    maxResults: 7,
                    categories: ['Address', 'Postal'],
                }),
            ],
            placeholder: 'Find location',
            expanded: true,
            collapseAfterResult: false,
            position: 'topleft',
            useMapBounds: false,
            zoomToResult: false,
        }).addTo(map);

        geocoder.on('results', ({ results }) => {
            const selectedResult = results && results[0];
            if (selectedResult) {
                map.panTo(selectedResult.latlng);
            }
        });
    }

    render() {
        return (
            <div className="map">
                <LeafletMap
                    center={...}
                    zoom=10
                    zoomControl={false}
                    ref={this.mapRef}
                />
            </div>
        );
    }
}
```

**Comment by jgravois** [comment]
just out of curiosity, why use a [Proxy Service](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/working-with-proxies/) to access the ArcGIS Online World Geocoder? No credits are consumed when users of your app perform searches.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-free-vs-paid.htm

**Comment by jgravois** [comment]
> I wonder if it makes a difference that I am using react-leaflet.

it doesn't appear to. i can't see the problem you reported in the app below and its virtually identical to what you shared in your snippet.

https://github.com/kboul/react-esri-leaflet-geosearch

i'm happy to investigate further, but only with a repro case.

**Comment by fungjj92** [comment]
I'm fine with closing this issue since it looks like it is not easily reproduced and we came to a good workaround. Thanks again for your attention!
