### ISSUE TITLE
Displaying wrong location

### ISSUE THREAD

**Issue by toeurtenh** [Esri/esri-leaflet-geocoder#211]
Hello team,

I am using esri.Geocoding.geocode to create marker using address. 

some of address display wrong location on the map, why? 

other thing
I copy these code from online for getting user's current location. it works fine for chrome but not for firefox. do i use right codes?

        //Load user's current location
        mymap.locate({ setView: true, maxZoom: 15 });

        mymap.on('locationfound', onLocationFound);
        function onLocationFound(e) {
            console.log(e);
            // e.heading will contain the user's heading (in degrees) if it's available, and if not it will be NaN. This would allow you to point a marker in the same direction the user is pointed. 
            L.marker(e.latlng).addTo(mymap).bindPopup('you are here').openPopup();;
        }

**Comment by jgravois** [comment]
> some of address display wrong location on the map, why?

"The accuracy of a match returned by a search depends on the amount and quality of information submitted." - ([reference](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-service-output.htm))

> I copy these code from online for getting user's current location. it works fine for chrome but not for firefox.

sorry, but thats not a problem we can help you with here.

**Comment by toeurtenh** [comment]
sorry, but thats not a problem we can help you with here. yes please help

**Comment by jgravois** [comment]
[![not gonna do it](https://i.ytimg.com/vi/4QHHGHve_N0/hqdefault.jpg)](https://www.youtube.com/watch?v=4QHHGHve_N0)

**Comment by toeurtenh** [comment]
sorry i don't get you

**Comment by jgravois** [comment]
that was just a cheeky way of saying that we cannot help with generic questions regarding HTML5 geolocation in Leaflet like the one you asked because they have nothing to do with the code for this plugin.

https://github.com/Esri/esri-leaflet/blob/master/CONTRIBUTING.md#before-filing-an-issue

**Comment by toeurtenh** [comment]
thank you, any recommendations of plugin?
