### ISSUE TITLE
Issues with Suggestions on Mobile

### ISSUE THREAD

**Issue by CsSingleton** [Esri/esri-leaflet-geocoder#213]
It seems that when using a mobile there is an issue with the suggestions not being clickable (when clicked it is as if I have clicked somewhere else on the map, closing the keyboard and not searching).

As a quick (temporary) fix, is there a way to turn off suggestions?
I have noticed people have brought this up already and that it should be fixed so hopefully its all on my side.

**Comment by jgravois** [comment]
sounds like a .css problem. i'd recommend putting together a simplified repro case to try and isolate the cause.

> As a quick (temporary) fix, is there a way to turn off suggestions?

there is not.

**Comment by pmacMaps** [comment]
I think this could possibly be related to issue #198.  I have a demo app using the 2.2.13 release of the plugin, and am still experiencing the issues I noted in #198.  My deployed apps have been kept back at release 2.2.6 to prevent this issue related to mobile devices.

**Comment by jgravois** [comment]
i couldn't reproduce this problem in [`v2.2.14`](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.2.14).

happy to chat more if anyone can provide additional information.
