### ISSUE TITLE
enhancement: add support for handwriting via a trackpad or handwriting pad

### ISSUE THREAD

**Issue by manesvenom** [Esri/esri-leaflet-geocoder#216]

**Comment by manesvenom** [comment]
The autocomplete location search suggestion does not work for non-english text input using handwriting pad on iOS 12.

**Comment by jgravois** [comment]
to be honest i have no idea what browser events we would need to listen to to support allowing users to enter addresses using a trackpad or stylus.

**Comment by manesvenom** [comment]
Below is my code change for tracking the handwriting via a trackpad / handwriting pad to listen the oninput event,
https://www.w3schools.com/jsref/event_oninput.asp

Added before line 741 v2.2.14
`    leaflet.DomEvent.addListener(this._input, 'input', function (e) {
      console.log('text change');
    }, this);
`


Added before line 826 in v.2.2.14
`    leaflet.DomEvent.addListener(this._input, 'input', leaflet.Util.throttle(function (e) {
        var key = e.which || e.keyCode;
        var text = (e.target || e.srcElement).value;

        // require at least 2 characters for suggestions
        if (text.length < 2) {
          this._suggestions.innerHTML = '';
          this._suggestions.style.display = 'none';
          leaflet.DomUtil.removeClass(this._input, 'geocoder-control-loading');
          return;
        }
          if (this._input.value !== this._lastValue) {
            this._lastValue = this._input.value;
            leaflet.DomUtil.addClass(this._input, 'geocoder-control-loading');
            this._geosearchCore._suggest(text);
          }
        
      }, 50, this), this);`

**Comment by jgravois** [comment]
thanks for taking the time to explain your tweak @manesvenom.

if you'd like to open a pull request, i'd be happy consider incorporating your change.

**Comment by jwasilgeo** [comment]
@manesvenom I'll close this for now since it has been awhile, but as @jgravois mentioned, we welcome pull requests if you'd like us to review your potential changes. Thanks.
