### ISSUE TITLE
Search features from local data (geojson)

### ISSUE THREAD

**Issue by DjKhireddine** [Esri/esri-leaflet-geocoder#218]
Hello,

I'm using esri-leaflet-geocoder to make double search
1) Search by adress. For that I use L.esri.Geocoding.arcgisOnlineProvider
2) Search feature from local data. ex:

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "name": "BUREAU"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          "7.6517",
          "48.5434"
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "32",
        "name": "Home"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          "7.7062",
          "48.5744"
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "53",
        "name": "SCHOOL"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          "7.7055",
          "48.5771"
        ]
      }
    }
  ]
}`

Can you help me please?

**Comment by jgravois** [comment]
my recommendation is that you store your GeoJSON in an ArcGIS Online hosted feature service. then you could easily wire up `L.esri.Geocoding.featureLayerProvider`.

if you'd rather extend this plugin to help you search flat GeoJSON, you're on your own: https://community.esri.com/thread/191726-leaflet-esri-geocoding-search-w-geojson-layers
