### ISSUE TITLE
Custom behaviour for click event on result

### ISSUE THREAD

**Issue by MadeByKarl** [Esri/esri-leaflet-geocoder#220]
Hello, sorry if this is somewhere in the doc, I couldn't find it anywhere.

I'd like to define my own behaviour when I click on a result from the Geosearch but I can't find where to bind it nor any pointers in the doc. Can anyone help me out?

Cheers!

**Comment by gavinr** [comment]
I do not see an extension point where that would be possible - but it's possible I'm missing something - @jgravois anything you can think of?

**Comment by jgravois** [comment]
extending [this sample](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) a bit:

```js
searchControl.on('results', function(data){
    results.clearLayers();
    for (var i = data.results.length - 1; i >= 0; i--) {
      const marker = L.marker(data.results[i].latlng).bindPopup('hello!');
      results.addLayer(marker);
    }
  });
``` 
https://leafletjs.com/reference-1.5.0.html#marker-bindpopup

**Comment by MadeByKarl** [comment]
Damn! Sorry for not replying sooner, I thought I already did!

Thanks for your answers. I didn't realize I could do it by using the results event as I thought it triggered on the autocompletion and not on the callback of selecting one of the suggestions.

So in short, that did it for me. Thanks!
