### ISSUE TITLE
Error during construction when not passing in any providers

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-geocoder#225]
Affects v2.3.0.  `this.options.providers` is undefined in `Geosearch.js` when no optional `providers` were configured, despite that when there are none set it _should_ default to using the ArcGIS Online World Geocoder.

A fix has been identified and I am working on it now.  Will add tests.

**Comment by gavinr** [comment]
Fix released in [v2.3.1](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.3.1)

**Comment by kjrhody** [comment]
Thank you!

**Comment by slutske22** [comment]
this mega screwed me up for a day, thank you for the fix

**Comment by jwasilgeo** [comment]
@slutske22 is it correct to assume you were using the "latest" NPM CDN URLs in your code that are listed in this repo's README?

```html
<link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder/dist/esri-leaflet-geocoder.css">
<script src="https://unpkg.com/esri-leaflet-geocoder"></script>
```

If so, it might help to specify the version you want to lock yourself to in the URLs to avoid this situation in the future, such as: 

- https://unpkg.com/esri-leaflet-geocoder@2.3.1/dist/esri-leaflet-geocoder.css
- https://unpkg.com/esri-leaflet-geocoder@2.3.1/dist/esri-leaflet-geocoder.js

Do you think it would help overall if we changed anything about this topic in this repo's README?

**Comment by slutske22** [comment]
I've been using the CDN link in my HTML header, linking to the latest version.  

`   
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />`
`
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>`

But I'm going to change it to the version-specific link you posted.  I also put this repo on my watch list to watch for version updates (as well as all the other repos I'm using CDNs with in my projects). This was actually a great lesson for me personally about how to reference external packages, and being mindful of versions.  I'm not sure you need to change the README, unless you want to make it more friendly to newbs like myself.  Thanks for the courtesy!

**Comment by jwasilgeo** [comment]
Thanks for the feedback and info, @slutske22, we appreciate it.

**Comment by kjrhody** [comment]
I had the same issue, I was using

```
    <link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder/dist/esri-leaflet-geocoder.css">
    <script src="https://unpkg.com/esri-leaflet-geocoder"></script>
```

per the instructions in the repo's README. I am also going to change it to the version-specific one as well. Thanks for the info!

**Comment by jwasilgeo** [comment]
Thanks for chiming in about this, too, @kjrhody.
