### ISSUE TITLE
locate and mark the location by given Latitude and longitude

### ISSUE THREAD

**Issue by xingguo3** [Esri/esri-leaflet-geocoder#240]
is there any API to locate a position by given Latitude and longitude? (lot and long are extracted from previous geosearch.)

**Comment by jgravois** [comment]
there is!

http://esri.github.io/esri-leaflet/api-reference/tasks/reverse-geocode.html

**Comment by xingguo3** [comment]
> there is!
> 
> http://esri.github.io/esri-leaflet/api-reference/tasks/reverse-geocode.html

Thanks for your reply.

But it is not what I want to know. What I really want to know is that:
when I have lat, long value in hand, how can I zoom map, locate to that position and add marker layer at that position. 

(it can be regarded as triggering resultsaction in geosearch, however, i don't know how to trigger that action or simulate that action)

**Comment by gavinr** [comment]
@xingguo3 adding a marker at a particular latitude/longitude is covered in the [Leaflet Quick Start Guide](https://leafletjs.com/examples/quick-start/) - I would recommend going though that.
