### ISSUE TITLE
TimeWait

### ISSUE THREAD

**Issue by o-ayoub** [Esri/esri-leaflet-geocoder#242]
Hi,
Is it possible to wait a x time before send request to server . 
I mean after user finish typing. 

thanks

**Comment by jgravois** [comment]
looking at the source code you can see that the `keyup` listener is throttled/debounced by 50 milliseconds. 
https://github.com/Esri/esri-leaflet-geocoder/blob/059a831609a239cf568a31cbff8d43028e1a0e3b/src/Controls/Geosearch.js#L400
you're welcome to substitute a different value and recompile the plugin yourself.

**Comment by o-ayoub** [comment]
That  s cool; Thank you so much @jgravois
