### ISSUE TITLE
FeatureLayerProvider: return suggestions that start with the input string

### ISSUE THREAD

**Issue by zzBNSF** [Esri/esri-leaflet-geocoder#244]
Hi,

Currently, the feature layer provider returns suggestions that contain the text that entered in the search box. It will be great if the provider can provide an option that returns only those suggestions that start with the search text.

It should be a simple change, and provides huge value to us. 

Thanks.
Jason Zou from BNSF Railway

**Comment by gavinr** [comment]
Hi - thanks for the request! I think the key here would be to have an option to not have the two percentage signs here:
https://github.com/Esri/esri-leaflet-geocoder/blob/059a831609a239cf568a31cbff8d43028e1a0e3b/src/Providers/FeatureLayer.js#L105

I'm not quite sure of the cleanest way to allow this input parameter though.

**Comment by zzBNSF** [comment]
A boolean type option can be introduced when create an instance. Yes to return suggestions that start with the input string, and false to contain the input like what implemented.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gavinr** [comment]
This was released in [v2.3.3](https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.3.3)
