### ISSUE TITLE
Multiple magic keys for provider L.esri.Geocoding.mapServiceProvider not geocoding correctly

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-geocoder#250]
In our `/debug/sample.html` and in the [public docs example](https://esri.github.io/esri-leaflet/examples/search-map-service.html) that uses a `mapServiceProvider` with the geocoder, an error is encountered when trying to query for the suggested result a user has chosen.

`TypeError: features is undefined`.

Somehow invalid numbers are getting added into the query URL structure, thus the query request doesn't happen and it is just returning an info json response.

`http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/2,2932/query?returnGeometry=true&where=1%3D1&outSR=4326&outFields=*&objectIds=2346&f=json`

Note specifically this part: `...MapServer/2,2932/query...`.

Here is a screenshot for some stack tracing.

![image](https://user-images.githubusercontent.com/4933392/82672485-083a5980-9c06-11ea-8d68-8a13d0d0f722.png)

**Comment by jwasilgeo** [comment]
Reproduction steps:

1. Go to <https://esri.github.io/esri-leaflet/examples/search-map-service.html>

1. Type in "fay" to get a few suggestion results, and focus on the "States and Counties" list of suggestions coming back from the MapServer's `find` REST call.

    ![image](https://user-images.githubusercontent.com/4933392/83273854-97a9b480-a192-11ea-9d16-f7418f8d1933.png)

1. Look at the DOM structure of those 2 suggestions.

    ![image](https://user-images.githubusercontent.com/4933392/83273926-b14afc00-a192-11ea-9eb0-8d7de3f082f2.png)

    The `["data-magic-key"]` attribute for each `<li>` turns out to be:
    - `"2268:2,2450:2,2596:2,3001:2"`
    - `"3079:2"`

    (Which is OBJECTID:LAYERID)

1. The "Fayette Detailed Counties" suggestion result has more than 1 magic key combo separated by commas because of how new DOM nodes are created and appended here. https://github.com/Esri/esri-leaflet-geocoder/blob/298916c6e8983ebac1a1750f80e264d2266b1928/src/Controls/Geosearch.js#L74-L88

    Look specifically at lines 74 and 85.  Because the MapServer's `find` REST response included more than 1 unique feature result with name "Fayette", the `else` block is appending more `["data-magic-key"]` attributes to that single `<li>` for the "Fayette Detailed Counties" suggestion result.

1. **Here comes the breakdown.**  Choose that suggestion result to arrive at the error where the geocoding `query` REST call's URL is malformed with `...MapServer/2,2450/query...`:

    ```
    https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/2,2450/query?returnGeometry=true&where=1%3D1&outSR=4326&outFields=*&objectIds=2268&f=json
    ```

1. The `2,2450` value comes from here, which **only works when there is one magic key**, but not when there are multiple ones with comma separation. https://github.com/Esri/esri-leaflet-geocoder/blob/298916c6e8983ebac1a1750f80e264d2266b1928/src/Providers/MapService.js#L53-L57

I am unsure at this time what the next steps are to go about fixing this situation. Ideas and comments welcome.

**Comment by jgravois** [comment]
this looks to be a bug i introduced in https://github.com/Esri/esri-leaflet-geocoder/issues/151

> do we list "Fayette Detailed Counties" multiple times in the DOM with only 1 magic key each?

no. IMHO a single result should appear in the list of suggestions and the control should return _all_ matching features in the event it emits when a geocode is executed.

to accomplish this, you could:
1. use the commas to create an array of keys
2. gather all the unique `featureId`s and group them by layer
3. make a call to `this.query` for each layer that contains a match
4. try and resolve/process more than one parallel response when necessary instead of just one.

f$%k all that noise though, it'd be a lot easier and probably work just fine to just trigger the `else` block anytime you have more than one match.

```js
// if more than one result is present, use find()
if (key && !key.includes(',')) {
} else {
  request = this.find().text(text).fields(this.options.searchFields).layers(this.options.layers);
}
```
you'll have to test with `featureLayerProvider` too though.

**Comment by jwasilgeo** [comment]
Thanks for the background info and ideas, @jgravois! I had a moment to give the latter idea a spin and it checks out nicely. Here's the mapped result without any errors for "Fayette".

![image](https://user-images.githubusercontent.com/4933392/83562363-0cf0ee80-a4df-11ea-8659-a8275abfc403.png)

I'll try to give this more time and thoroughly test it out (and also double-check with the FL provider) in the coming days.

**Comment by jwasilgeo** [comment]
FL providers queries correctly when there are more than 1 keys available.  Added comments and tests.
