### ISSUE TITLE
the search failed our load test with 60+ users

### ISSUE THREAD

**Issue by zzBNSF** [Esri/esri-leaflet-geocoder#254]
In our project, we use L.esri.Geocoding.Geosearch control for users to search locations. We had performed load tests over the past weekend. It worked great with up to 55 users. But it started failing when the user count was over 60. I am wondering if there is any limitation of number of concurrent users that can perform the location search with the GeoSearch control, which behind the scene uses the esri-leaflet-geocoder.

Thanks,
Jason Zou

**Comment by jgravois** [comment]
it looks like the World Geocoding Service was experiencing issues on 6/13/2020.

http://status.arcgis.com

![Screen Shot 2020-06-16 at 2 44 59 PM](https://user-images.githubusercontent.com/3011734/84831339-fb7c0c00-afdf-11ea-9a16-9a9856ef642a.png)

**Comment by zzBNSF** [comment]
Thanks, John! So basically no limitation of concurrent users using the Geosearch control, correct?

**Comment by jgravois** [comment]
not that i've ever heard of. 🤷

**Comment by zzBNSF** [comment]
Make sense. Thank you John!
