### ISSUE TITLE
Styling search input

### ISSUE THREAD

**Issue by adrianratajczak** [Esri/esri-leaflet-geocoder#255]
Hi, I am looking for any option to style search input on map. 
I know that there is almost no way to move it outside map container, but solution for that is better (for my purpose) searchbar styling. 
I mean something like fixed searchbar on top of map.
There is any way to achive that?

**Comment by jgravois** [comment]
see https://github.com/Esri/esri-leaflet-geocoder/issues/32#issuecomment-248769662

**Comment by jwasilgeo** [comment]
Hi @adrianratajczak. I'd like to close this since it has been awhile, but feel free to continue discussing/reopening if you wish.
