### ISSUE TITLE
Manage to disable 'searchExtent' param to suggest requests

### ISSUE THREAD

**Issue by Hugo01** [Esri/esri-leaflet-geocoder#257]
I'm doing some very specific stuff on leaflet right now and I wonder if it is possible to NOT pass dynamically the searchExtent param

**Comment by jgravois** [comment]
https://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html


Option | Type | Default | Description
-- | -- | -- | --
useMapBounds | Boolean or Integer | 12 | Determines if and when the geocoder should use the bounds of the map to filter search results. If true the geocoder will always return results in the current map bounds. If false it will always search the world. If an integer (like 11) is passed, the geocoder will use the bounds of the map for searching only if the map is currently zoomed in far enough.

**Comment by jwasilgeo** [comment]
Thanks for the clarification @jgravois.

@Hugo01I'll close this now with the hopes this is what you needed and that it works for you. Of course feel free to reopen if you encounter any difficulties or problems with this.

**Comment by jwasilgeo** [comment]
Thanks for the clarification @jgravois.

@Hugo01 I'll close this now with the hopes this is what you needed and that it works for you. Of course feel free to reopen if you encounter any difficulties or problems with this.
