### ISSUE TITLE
two search fields in the input form?

### ISSUE THREAD

**Issue by mkden** [Esri/esri-leaflet-geocoder#267]
how to do like this?
please, help.
![123](https://user-images.githubusercontent.com/3009419/110912290-d1643a00-8324-11eb-9ae3-5e4e01bf98fd.jpg)

**Comment by pmacMaps** [comment]
Are you asking how to change where the search form is located on the webpage?  Or are you asking something different?

**Comment by mkden** [comment]
yes and add one more search field instead of one there should be two!
two fields input autocomplete

**Comment by mkden** [comment]
???????????????????????????????

**Comment by pmacMaps** [comment]
I'm still trying to understand your goal.  From the graphic, it appears you want the search control UI to not be located on the map?  And that you want to be able to search multiple fields within a feature service?

Here is a sample map that does both: https://gis.ccpa.net/sld/activity/.

I'm just trying to better understand your goals to help identify a solution.

**Comment by jwasilgeo** [comment]
@pmacMaps thanks for jumping in and helping!

@mkden hope this info helps you out.

**Comment by tomik23** [comment]
But from what I can see you need the autosuggestion library with geocoding capability :)
Take a look at [my example](https://tomik23.github.io/leaflet-examples/#40.distance-between-cities-on-map)

![select-two-city](https://user-images.githubusercontent.com/25438490/119383464-a81c3e80-bcc3-11eb-9f5e-23a210f20a85.png)
 
You can adapt it to your own needs.

**Comment by jwasilgeo** [comment]
Hej dziekuje @tomik23 for sharing your own leaflet examples site. Nice community resource for folks using LeafletJS in different ways.

@mkden, as @pmacMaps noted you can use the `esri-leaflet-geocoder` to accommodate your goals by putting multiple instances of it in another container element outside of the map.

**Comment by mkden** [comment]
> But from what I can see you need the autocomplete library with geocoding capability :)
> Take a look at [my example](https://tomik23.github.io/leaflet-examples/#40.distance-between-cities-on-map)
> 
> ![select-two-city](https://user-images.githubusercontent.com/25438490/119383464-a81c3e80-bcc3-11eb-9f5e-23a210f20a85.png)
> 
> You can adapt it to your own needs.

you showed me an example on https://nominatim.openstreetmap.org
and I asked https://geocode.arcgis.com
