### ISSUE TITLE
Update imported version of esri-leaflet to 3.0.2

### ISSUE THREAD

**Issue by jon571** [Esri/esri-leaflet-geocoder#272]
Esri-leaflet recently made a change here:
https://github.com/Esri/esri-leaflet/commit/a6a46fca47dba7bae12b54bcaddf37963d3b55b0

This is to stop an error issued by webpack 5, in my case after upgrading to angular 12:
./node_modules/esri-leaflet-geocoder/node_modules/esri-leaflet/src/EsriLeaflet.js:2:0-51 - Error: Should not import the named export 'version' (reexported as 'VERSION') from default-exporting module (only default export is available soon)

**Comment by gavinr** [comment]
I think you can do this yourself - just run:

```
npm install
npm install esri-leaflet@3.0.2
```

**Comment by jgravois** [comment]
you can, but 3x is outside the SemVer range defined in the package.json
https://github.com/Esri/esri-leaflet-geocoder/blob/master/package.json#L13

**Comment by gavinr** [comment]
Ah, good point. I suppose we should have included that (`"esri-leaflet": "^3.0.0"`) in v3.0 release.

**Comment by jgravois** [comment]
meh. live and learn! 😸

**Comment by jon571** [comment]
Any idea when there might be a release available on npm for this?

Cheers :-)

**Comment by gavinr** [comment]
This was released in v3.1.0
