### ISSUE TITLE
How to import it using npm?

### ISSUE THREAD

**Issue by ameerdhi7** [Esri/esri-leaflet-geocoder#279]

**Comment by jwasilgeo** [comment]
@ameerdhi7 is there more information you can provide to help us with your question?

If you are trying to import it in your JS code, this "frequently asked question" issue thread might be helpful for you: https://github.com/Esri/esri-leaflet-geocoder/issues/219#issuecomment-516139507

**Comment by ameerdhi7** [comment]
i was just unaware of how to use leaflet controls and stuff, so im closing this issue
