### ISSUE TITLE
L.esri.Geocoding.reverseGeocode not accepting API key

### ISSUE THREAD

**Issue by GuidoTapia** [Esri/esri-leaflet-geocoder#282]
This error seems to be related to #277, using version 3.1.1 I'm having this response: 
`{code: 499, message: 'Token Required', details: Array(0)}`
I had no problems with Geocode using:
http://esri.github.io/esri-leaflet/api-reference/tasks/geocode.html

additional: in the files changed for fix #278 I found that reverseGeocode has some differences with geocode in setters and run function

**Comment by gavinr** [comment]
@GuidoTapia we have updated the README: https://github.com/Esri/esri-leaflet-geocoder#terms-and-conditions ... I think that may help you out.

If you're still having issues please post some example code and we'd be happy to help.

**Comment by gavinr** [comment]
@GuidoTapia the reverseGeocode issue was fixed in v3.1.3: https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v3.1.3

**Comment by jgravois** [comment]
i'd definitely recommend updating the documentation to make the new requirement clear and show folks how to inject their own token.

https://developers.arcgis.com/esri-leaflet/api-reference/tasks/reverse-geocode/

**Comment by gavinr** [comment]
Thanks @jgravois, good catch. I'll get that updated.
