### ISSUE TITLE
Support sourceCountry as a parameter/option

### ISSUE THREAD

**Issue by wrhwebmaster** [Esri/esri-leaflet-geocoder#38]
It is highly desirable to:
Control GeoCoding Search to be "limited to US Addresses only".
The US Addresses that I'm thinking of, would includes:
Hawaii, Alaska, the US Main Land, American Samoa, Guam, Puerto Rico/Virgin Islands, and territories like that. See http://www.weather.gov, for a map display, if needs be.

I'm sure if I was in Europe, France, and I would have wanted to filter all of my
geoSearch be limited to France, I would have asked something similar.

The attached image, shows non-desirable searches that presently would display, by default.
We would NOT have the weather information for non-US locations.
![control_geo_search_so_that_only_us_addresses_are_searched](https://cloud.githubusercontent.com/assets/4999046/3921260/bbf4b698-23bf-11e4-90fc-70f563ee3d6c.png)

**Comment by wrhwebmaster** [comment]
We are still awaiting for a positive outcome of what we opened as a ticket here, back in Aug 2014.
Appreciate a feedback, please.

**Comment by jgravois** [comment]
to recap what's been said to date: the Esri Leaflet Geosearch control does not yet incorporate an option to specify an input sourceCountry because the 'suggest' operation of the geocoding service itself does not yet make it available.

@patrickarlt made a few suggestions in November related to possible changes to consider in this plugin, but we haven't gone ahead with anything yet (partly because we haven't got any more specific feedback indicating what would be the most helpful.

for me it seems a little confusing that the existing control constructor option `useMapBounds` only inserts  optional `location` and `distance` because these parameters help rank results based on their proximity to the current center of the map, but don't restrict results outside.

perhaps the simplest solution would be to insert the current map extent as `searchExtent` in suggest requests dynamically when developers have set the appropriate flag?

[here](https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Tasks/Suggest.js#L24)
`this.params.searchExtent = L.esri.Util.boundsToExtent(bounds);`

**Comment by wrhwebmaster** [comment]
Summary (from my email conversation with Sam L @ESRI, on 2015-March-10):
This request is for sourceCountry to be added at the /suggest endpoint (not only at /find).
At present for "/suggest" we could do the following: 
(&searchExtent=-94.602026,39.083630,-94.570151,39.109774)
--- but NOT the following: "&sourceCountry=USA"
Please set a boundary that would show USA only.

**Comment by jgravois** [comment]
> This request is for sourceCountry to be added at the /suggest endpoint (not only at /find).

i am happy to pass this information along to the development team that maintains our World Geocoding Service, but i also took the liberty of writing up a sample to add the capability of defining a static search extent to the Geosearch control and leveraging it from your own app...
```
// sw, ne
var usBounds = new L.LatLngBounds([25,-125], [45,-65]);

L.esri.Geocoding.Controls.geosearch({
  staticBounds: usBounds
}).addTo(map);
```
the relevant changes to the geocoder plugin can be found [here](https://github.com/jgravois/esri-leaflet-geocoder/commit/2a1958fcfdf64ebb695cf124056fce3cf7d0b1bc?diff=split)

i'm happy to provide further assistance, but i'd need to know exactly what you need help with.

**Comment by wrhwebmaster** [comment]
Thanks, JGravois.
You could take a look at what we are doing here (it is not map-centric):
http://www.wrh.noaa.gov/wrh/test/geosearch2.php
The PHP page would stay there for a short period of time.

What we would like to do, is to get "rid" of the different 
'drop-down/search bounds/areas' and simply go against 
'one unified' USA.
See Goolge's geoSearch implementation here (restricted to USA only):
http://www.wrh.noaa.gov/wrh/test/geosearchV3.php
 
'One unified' USA boundary would be:
The United States consists of the 48 adjoining U.S. states plus Washington, D.C. (federal district), on the continent of North America. Adding to that, states of Alaska and Hawaii and all off-shore United States territories and possessions, which include American Samoa, Guam, the Northern Mariana Islands, Puerto Rico, and the United States Virgin Islands.

**Comment by jgravois** [comment]
thanks @wrhwebmaster.  i passed on your (and @robertd's) interest in the World Geocoding Service `suggest` operation both (a) supporting sourceCountry and (b) including an option to denote 'USA + territories' in requests back in November of 2014.

we will continue to leave this esri-leaflet issue open, but please be aware that this is primarily to serve as a reminder to make sure the functionality is included in this API once its made available in the service itself.

**Comment by jgravois** [comment]
quick reference test [here](http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest?text=paris&sourceCountry=USA&f=json) will return `Paris, Texas` once the World Geocoding Service `suggest' operation supports `sourceCountry`

**Comment by robertd** [comment]
Is that only for contiguous US?

**Comment by jgravois** [comment]
not sure what you mean.  suggest still doesn't support passing in `sourceCountry` at all.

**Comment by patrickarlt** [comment]
The doc for using `countryCode` with `suggest` is live but it does not appear to be working. I'm checking in with the geocoding team to see if this will be supported and if multiple country codes can be used.

At any rate since this issue is so old i'll probably do a 1.1.0 release with this as a new option.

**Comment by patrickarlt** [comment]
@wrhwebmaster with the upcoming online release you will be able to specify `sourceCountry` on `/suggest` however it will only accept 1 country value (i.e `USA`, `GUM`, ect...) so the best you will be able to do is all 50 states + DC with  `sourceCountry=USA` and leave out Puerto Rico ect...

The geocoding team has conformed that support for multiple values for `sourceCountry` is a known feature and they plan to include it in their next release so you will be able to do `sourceCountry=USA,GUM,PRI,ASM,VIR` in the **next** release.

The other alternative now that ArcGIS Server 10.3 supports `/suggest` is to purchase [Street Map Premium](http://www.esri.com/data/streetmap) and get up your own geocoder with a subset of the data that covers all 50 states + territories. Let me know if this option interests you.

**Comment by patrickarlt** [comment]
@wrhwebmaster This will be supported in the next version `v2.0.0-beta.4`. However I am not going to add support for this to the 1.X.X branch.

It also appears (contrary to the doc) that multiple countries DO work. This will all be in a release next week so you will be able to do this:

```js
L.esri.Geocoding.geosearch({
  providers: [
    L.esri.Geocoding.arcgisOnlineProvider({
      countries: ['USA', 'GUM', 'VIR', 'PRI'], // search only US, Guan, Virgin Islands and Puerto Rico
      categories: ['Address', 'Postal', 'Populated Place', ] // Don't search POIs
    })
  ]
}).addTo(map);
```
