### ISSUE TITLE
Option to not put a marker at found location

### ISSUE THREAD

**Issue by reyemtm** [Esri/esri-leaflet-geocoder#61]
Maybe I am missing the option, but if it does not exist it would be nice to have an option to not put a placeholder/marker at the found location. Once the location is found the placeholder does not go away until another place is found via search or the map is reloaded, so the user needs some way to either remove the placeholder/marker or just not have one at all.

**Comment by jgravois** [comment]
you're talking about L.esri.Geocoding.Controls.Geosearch correct?

please take a look at [this](http://esri.github.io/esri-leaflet/examples/search-map-service.html) sample.  whether or not you leverage a custom provider, the control doesn't add markers to the map automatically.  it's necessary to wire up an event listener and add markers for 'results' manually (as we do [here](http://esri.github.io/esri-leaflet/examples/geocoding-control.html)).

**Comment by reyemtm** [comment]
Oh great, I knew I missed something. Thanks.
