### ISSUE TITLE
Option to authenticate with Geocode Service

### ISSUE THREAD

**Issue by mattgolsen** [Esri/esri-leaflet-geocoder#62]
I'm attempting to geocode against a server that requires authentication, but the geocoder plugin doesn't seem to support an option for authentication. Am I misunderstanding the proper method?

**Comment by jgravois** [comment]
which specific object in the constructor are you instantiating?

L.esri.Geocoding.Tasks.[Geocode](https://github.com/esri/esri-leaflet-geocoder#lesrigeocodingtasksgeocode) inherits from L.esri.Tasks.[Task](http://esri.github.io/esri-leaflet/api-reference/tasks/task.html) so you can call `token('mytoken')` prior to calling `run()` if you need to authenticate.

**Comment by mattgolsen** [comment]
Ah, I didn't realize that. Thanks for the clarity, it helped considerably.
