### ISSUE TITLE
Support for ArcGIS Server 10.3 Geocoder?

### ISSUE THREAD

**Issue by tomweis** [Esri/esri-leaflet-geocoder#64]
Hi, wanted to check and see if any updates were planned to support the new and depreciated functionality in ArcGIS Server 10.3 Geocode service?  I'm trying to switch the plug-in from using the Esri world geocode service to a locally hosted 10.3 geocode service.  Any tips?

NEW:  With suggestions now available at 10.3 and I'd like to take advantage of those and plug my geocoder in as a provider while disabling the ArcGIS Online World Geocoder.

Depreciated:  At 10.3 the Find operation of a Geocode service does not return an Extent, as it did in prior versions.  As a result, adding a 10.3 geocode service as a provider does not work.

Thanks!

**Comment by jgravois** [comment]
i've found a few public [10.3](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/Composite_HBR_Asset/GeocodeServer) geocoding service, but none of them includes a new `suggest` operation.  is yours public by chance?

**Comment by tomweis** [comment]
It's there but hidden in the supported operations list:  http://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/Composite_HBR_Asset/GeocodeServer/suggest

I'm working on a solution using jQuery but it would be nice to have it supported though the plug-in.

**Comment by jgravois** [comment]
i think its a bug that you can root your way to 'suggest' for that geocoding service that was upgraded from a previous version of ArcGIS Server because its not really functioning (see [example](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/Composite_HBR_Asset/GeocodeServer/suggest?text=123&category=&location=&distance=&f=html))

**Comment by tomweis** [comment]
Possibly the server was upgraded without rebuilding the locator behind it with 10.3, or the suggest capability is not enabled. Could be why "suggest" isn't listed in the supported operations.  I'll see if I can get a public 10.3 geocode service published that meets the requirements.  Thanks for following up!

See the API help: http://sampleserver6.arcgisonline.com/arcgis/sdk/rest/index.html#/Suggest/02ss000000q2000000/

- The address locator from which the geocode service was published must support suggestions. Only address locators created using ArcGIS 10.3 for Desktop and later can support suggestions. See the Create Address Locator geoprocessing tool help topic for more information.
- The geocode service must have the Suggest capability enabled. Only geocode services published using ArcGIS 10.3 for Server or later support the Suggest capability.

**Comment by goldenlimit** [comment]
@tomweis you are right.
So the right way to make sure the suggest is enabled is to republish the server and check on "suggest" capability. Here is the screenshot for your reference: 
![suggestions](https://cloud.githubusercontent.com/assets/5265346/8465133/62ffb116-1ffc-11e5-9fff-f0a2a10fdc74.JPG)
