### ISSUE TITLE
Packaged versions of application (both mac and windows) fails to load results returned by Geocoder

### ISSUE THREAD

**Issue by murtaza-webonise** [Esri/esri-leaflet-geocoder#66]
I am using  esri-leaflet-geocoder like this
" var geocoderControl = new L.esri.Controls.Geosearch({
        expanded : true,
        collapseAfterResult : false,
        useArcgisWorldGeocoder : false,
        allowMultipleResults : true,
        useMapBounds : false,
        });"
But when I create packaged version of my application that is its .exe or .dmg then I do not see suggested results it seems like esri-geocoder is not able to load the results.

**Comment by jgravois** [comment]
just off the top of my head, if you aren't seeing suggested results i'd recommend using something like [Fiddler](http://www.telerik.com/fiddler) to snoop the network traffic in your app and confirm that you are sending out valid web requests.

with regard to your architecture, i have pretty much *no* idea what you're talking about.  exactly how/why are you compiling a JavaScript project into native windows and mac applications?

**Comment by murtaza-webonise** [comment]
It is not a Javascript project it is a Java based project(JavaFX) in which we can load html files along with it's JSs using WebView and WebEngine. So, basically I have one html file which contains map and  it's corresponding JS contains code related to esri-geocoder and the the way JavaFx loads it.

 webEngine.load(path to HTML file);

**Comment by patrickarlt** [comment]
@murtaza-webonise if you set `useArcgisWorldGeocoder` to false but fail to provide any other options for the Geocoder to search for via the `providers` option (https://github.com/Esri/esri-leaflet-geocoder#options) this is the excepted behavior.

**Comment by patrickarlt** [comment]
@murtaza-webonise `useArcgisWorldGeocoder` is now deprecated in 2.0.0 so you MUST pass at least one provider so this will now throw an error.

**Comment by murtaza-webonise** [comment]
Perfect Thanks!
