### ISSUE TITLE
Geocoding map attribution should be an option

### ISSUE THREAD

**Issue by npeihl** [Esri/esri-leaflet-geocoder#67]
Since using the ArcGIS Online Geocoding service is an option the [map attribution text](https://github.com/Esri/esri-leaflet-geocoder/blob/8ace0a6e605a3b0b8047f28a8e1340638c79ff70/src/Controls/Geosearch.js#L237-L239) should also be an option in the constructor. The default option could remain "Geocoding by Esri".

**Comment by jgravois** [comment]
agreed.

a PR would be helpful, otherwise I'll knock it out sometime soon.

**Comment by npeihl** [comment]
I'll take a 🔪 at it.

**Comment by jgravois** [comment]
awesome!
