### ISSUE TITLE
Does not work on IE11

### ISSUE THREAD

**Issue by Rrivera5127** [Esri/esri-leaflet-geocoder#69]
Cannot click a suggestion in the dropdown in IE 11 on sample site. Enter key doesn't seem to work either.

**Comment by Rrivera5127** [comment]
looks like it's just an old version on the demo page. The current code in github does work in IE 11.

broken: http://esri.github.io/esri-leaflet/examples/geocoding-control.html

**Comment by jgravois** [comment]
can you explain in a little more detail what you mean?  that sample loads version 1.0.0 rc4 of the geocoder widget, which is the latest release.

**Comment by jgravois** [comment]
nm.  now i understand that you're saying changes to the live code since rc4 seem to have resolved the problem.  i'll confirm and see about tagging a new release after we merge support for suggest with custom geocoding services (here #65)
