### ISSUE TITLE
Add option for sourceCountry

### ISSUE THREAD

**Issue by ajturner** [Esri/esri-leaflet-geocoder#72]
As a Developer, I would like to limit world geocoder results to a specific country (e.g. `USA`)

the [Geocode API](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm#ESRI_SECTION1_E8390AE55A67457A99B5A9E2E3F54FBC) accepts `sourceCountry=USA`. so this would be an option passed into locators that would only be used by certain providers.

**Comment by jgravois** [comment]
looks like a duplicate of #38, correct?

**Comment by ajturner** [comment]
yes - good call @jgravois - what's the blocker for doing the simple option now?

**Comment by jgravois** [comment]
sorry, but not sure i follow you.  if you are referring to the [simple option](https://github.com/Esri/esri-leaflet-geocoder/issues/38#issuecomment-71545244) of applying a filtering bounding box dynamically, that was [merged](https://github.com/Esri/esri-leaflet-geocoder/pull/58) shortly after our last tagged release.  

i have [one more](https://github.com/Esri/esri-leaflet-geocoder/pull/65) PR that needs reviewed/merged, then we can tag again.  in the meantime you can also build from `master`.

let me know if i'm missing anything or if you can use a hand.
