### ISSUE TITLE
are we ready to tag a 1.0.0 release?

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-geocoder#74]
i assume we're going to follow @ngoldman's advice [here](https://github.com/Esri/esri-leaflet/issues/577#issuecomment-119680941) for plugins as well and make the final 0.7.3 Leaflet compatible release `1.0.0` (with no release candidate qualifier).

i was anxious to tag esri-leaflet-geocoder as soon as we'd incorporated support for 'suggest' from custom geocoding services, but perhaps i should wait until we finally see a Leaflet 1.0.0.beta1 announcement?  or maybe since nothings going to change with `0.7.3` we can just get started publishing our `1.0.0` releases now?

**Comment by jgravois** [comment]
i'll work on refactoring this plugin to account for the changes introduced in Esri/esri-leaflet#581

**Comment by patrickarlt** [comment]
@jgravois We are going to do this actually:

* Esri Leaflet 1.0.0 requires Leaflet 0.7.3
* Esri Leaflet 2.0.0 requires Leaflet 1.0.0

The version mismatch sucks but we can now take full advantage of SemVer and the upgrade IS a major release since everything will be a breaking change.
