### ISSUE TITLE
Don't perform query on empty input

### ISSUE THREAD

**Issue by acartas** [Esri/esri-leaflet-geocoder#88]
When a user clicks enter but no query is placed, should ignore the input and not run a search or display the "No results" dropdown.

I made a small edit in my own copy in the "geocode" function of the Geocoders that simply returns if (query.length == 0) that works. I'm not very familiar with using github though or the rest of the code, so I'll just mention it and leave it up to someone else to add to the on-line code if they'd like.

**Comment by acartas** [comment]
Well, step 1 of being bad at github, this is not the code I meant to comment on. Ignore this.

**Comment by jgravois** [comment]
did you mean to submit [here](https://github.com/Esri/arcgis-dijit-geocoder-js)?
