### ISSUE TITLE
confusion in docs related to geosearch events

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-geocoder#91]
in creating a doc page for `L.esri.Geocoding.geosearch` i noticed some problems with the doc page in this repo's README

1. the control doesn't fire a `loading` event
2. the control says the `load` event corresponds with a request being started, but the event is actually triggered immediately before `results`.

seems like we either need to fix when `load` actually fires or drop it altogether.

we also need to make a decision about whether to duplicate the API reference for plugins in individual repo READMEs and the main esri-leaflet site or remove them from READMEs altogether.  seems easiest to just remove it from here once the updates to the esri leaflet website are in place and skip managing both.

**Comment by patrickarlt** [comment]
`load`/`loading` follows the Leaflet API convention

* Fire `loading` when something starts loading
* Fire `load` when it is done.

So `load` firing just before `results` is actually what should happen. Taking another look at this `load` only fire when when you ask for results (after you hit Enter).

Ideally `load`/`loading` should happen for suggestions too.

**Comment by jgravois** [comment]
thanks for this.  i'll work on updating the doc and injecting a `loading` emitter into geocode and perhaps both into suggestions.

**Comment by jgravois** [comment]
shelfing this for now.
